In [1]:
import pandas as pd
import os
from typing import Optional
from src.data.loading import DataLoader
from src.features.feature_engineering import FeaturesMaker

In [2]:
dl = DataLoader()
store_sales = dl.load_store_sales('../data/store_sales.csv')
store_sales_dates = dl.load_dates('../data/store_sales_dates.csv')

In [3]:
fm = FeaturesMaker()
fm.make_features(store_sales, 'cnt', 93, 7, store_sales_dates)

,store_id,item_id,date,cnt,cnt_lag_94,cnt_lag_95,cnt_lag_96,cnt_lag_97,cnt_lag_98,cnt_lag_99,cnt_lag_100,event_name,event_type,weekday,day,month,year
0,STORE_1,STORE_1_555,2011-01-29,51,0,0,0,0,0,0,0,not_event,not_event,5,29,1,2011
1,STORE_1,STORE_1_555,2011-01-30,45,0,0,0,0,0,0,0,not_event,not_event,6,30,1,2011
2,STORE_1,STORE_1_555,2011-01-31,25,0,0,0,0,0,0,0,not_event,not_event,0,31,1,2011
3,STORE_1,STORE_1_555,2011-02-01,39,0,0,0,0,0,0,0,not_event,not_event,1,1,2,2011
4,STORE_1,STORE_1_555,2011-02-02,23,0,0,0,0,0,0,0,not_event,not_event,2,2,2,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5452,STORE_3,STORE_3_586,2016-01-17,101,82,77,97,98,123,126,104,not_event,not_event,6,17,1,2016
5453,STORE_3,STORE_3_586,2016-01-18,66,101,82,77,97,98,123,126,MartinLutherKingDay,National,0,18,1,2016
5454,STORE_3,STORE_3_586,2016-01-19,62,114,101,82,77,97,98,123,not_event,not_event,1,19,1,2016
5455,STORE_3,STORE_3_586,2016-01-20,68,117,114,101,82,77,97,98,not_event,not_event,2,20,1,2016
5456,STORE_3,STORE_3_586,2016-01-21,69,71,117,114,101,82,77,97,not_event,not_event,3,21,1,2016